alias: Airbnb Booking Handler
description: "Handles incoming Airbnb booking webhooks and updates input_text entities."

trigger:
  - platform: webhook
    webhook_id: room_a_booking
    allowed_methods:
      - POST
      - PUT
    local_only: true

  - platform: webhook
    webhook_id: room_b_booking
    allowed_methods:
      - POST
      - PUT
    local_only: true

variables:
  payload: "{{ trigger.json.bookings }}"
  room_a_bookings: >-
    {{ payload
       | selectattr('room', 'defined')
       | selectattr('room', 'search', 'ROOM A KEYWORD')
       | list }}
  room_b_bookings: >-
    {{ payload
       | selectattr('room', 'defined')
       | selectattr('room', 'search', 'ROOM B KEYWORD')
       | list }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ room_a_bookings | length > 0 }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.room_a_booking_json
            data:
              value: "{{ room_a_bookings | to_json | string | replace(' ', '') }}"

      - conditions:
          - condition: template
            value_template: "{{ room_b_bookings | length > 0 }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.room_b_booking_json
            data:
              value: "{{ room_b_bookings | to_json | string | replace(' ', '') }}"

  - service: persistent_notification.create
    data:
      title: "Airbnb Booking"
      message: >
        Updated bookings:
        room_a: {{ room_a_bookings | length }},
        room_b: {{ room_b_bookings | length }}

mode: single
